### ISSUE TITLE
Implement i18n for Multi-Language Support (French & English)

### ISSUE THREAD

**Issue by ExcelDurant** [whilesmart/lasodec#11]
The project should support both English and French. Aspects of the project, including the frontend and backend, should be translated properly based on the user's language preference.

To implement `i18n` effectively, we need to take a few steps, such as:

- Updating the database to support multiple languages
- Creating language files and adding translations for each language
- Using the Laravel translation functions in the codebase to dynamically switch between the languages
- Updating the views with appropriate language tags, so that content is displayed in the correct language based on user preference

**Comment by jpenanje** [comment]
> The project should support both English and French. Aspects of the project, including the frontend and backend, should be translated properly based on the user's language preference.
> 
> To implement `i18n` effectively, we need to take a few steps, such as:
> 
> * Updating the database to support multiple languages
> * Creating language files and adding translations for each language
> * Using the Laravel translation functions in the codebase to dynamically switch between the languages
> * Updating the views with appropriate language tags, so that content is displayed in the correct language based on user preference

Please at what level are you? I have started creating the language files for the various pages.

**Comment by ExcelDurant** [comment]
> > The project should support both English and French. Aspects of the project, including the frontend and backend, should be translated properly based on the user's language preference.
> > To implement `i18n` effectively, we need to take a few steps, such as:
> > 
> > * Updating the database to support multiple languages
> > * Creating language files and adding translations for each language
> > * Using the Laravel translation functions in the codebase to dynamically switch between the languages
> > * Updating the views with appropriate language tags, so that content is displayed in the correct language based on user preference
> 
> Please at what level are you? I have started creating the language files for the various pages.

A PR for this issue will soon be merged. Please wait a little bit

**Comment by Fenn-CS** [comment]
@ExcelDurant Why is the PR not linked here?
