### ISSUE TITLE
Create model `ExpertProfile`

### ISSUE THREAD

**Issue by ExcelDurant** [whilesmart/lasodec#13]
The model would contain information about each expert in the directory, including their name, area of expertise, contact information, and any other relevant details.

Some key properties to be added to the `User` model are:
- `user_id`: url to profile image
- `status`
- `location`: location of the user
- `details`: text explaining the expert's skills

**Comment by Fenn-CS** [comment]
@ExcelDurant Updated this, let's create a new model `ExpertProfile` that belongs to user instead of adding field `is_expert` to user model.
