### ISSUE TITLE
Create `Blog` model

### ISSUE THREAD

**Issue by ExcelDurant** [whilesmart/lasodec#16]
A new `Blog` model should be added to the project, with the following key properties:

- `title`: the title of the blog post
- `content`: the full text content of the blog post
- `author`: the author of the blog post
- `published_at`: the publish date of the blog post
- `slug`: the URL-friendly version of the blog post's title for SEO purposes
- `description`: a simple description of the blog post
- `image`: a url to the blog post's image

**Comment by Fenn-CS** [comment]
Would be closed by : https://github.com/whilesmart/lasodec/issues/18
