### ISSUE TITLE
Create `Story` model

### ISSUE THREAD

**Issue by ExcelDurant** [whilesmart/lasodec#17]
we need to add a `Story` model to store and manage short stories. The `Story` model will have similar functionality to the `Blog` model, allowing us to easily create, update, and delete short stories and display them.

The key properties will be:
- `title`: the title of the short story
- `content`: the full text content of the short story
- `author`: the author of the short story
- `published_at`: the publish date of the short story
- `slug`: the URL-friendly version of the short story's title for SEO purposes
- `description`: A short description of the story

**Comment by Fenn-CS** [comment]
Would be closed : https://github.com/whilesmart/lasodec/issues/18
