### ISSUE TITLE
Create `Article` model

### ISSUE THREAD

**Issue by ExcelDurant** [whilesmart/lasodec#18]
We need to add a `Article` model to store and manage news articles. The `Article` model will allow us to easily create, update, and delete news articles, as well as display them

It may have the following key properties:
- `title`: the title of the news article
- `content`: the full text content of the news article
- `author`: the author of the news article
- `published_at`: the publish date of the news article
- `category`: the category of the news article (e.g. sports, politics, entertainment)
- `slug`: the URL-friendly version of the news article's title for SEO purposes
- `image`: a url to the news article's image

**Comment by Fenn-CS** [comment]
This is the exact same thing as https://github.com/whilesmart/lasodec/issues/16 and https://github.com/whilesmart/lasodec/issues/16

So, close those and I would update this to be one model called `Article`
