### ISSUE TITLE
Update footer social media links

### ISSUE THREAD

**Issue by ExcelDurant** [whilesmart/lasodec#42]
We need to update the links in the footer that direct users to the company's social media accounts on platforms such as Facebook, Instagram, Twitter, Youtube, and LinkedIn. Any existing social media icons that are not associated with the company should be removed

**Comment by Merine303** [comment]
Social Media handles for LACSODEC pending creation. We will use that of LUKMEF for now

**Comment by jpenanje** [comment]
> Social Media handles for LACSODEC pending creation. We will use that of LUKMEF for now

Are you on in? If not let me be in charge of doing that
