### ISSUE TITLE
Current page navbar link should be active

### ISSUE THREAD

**Issue by ExcelDurant** [whilesmart/lasodec#43]
The links on the navbar do not become active when we navigate to different pages. The home link remains active on all pages. Normally it is the link of the current page that needs to be active

**Comment by jpenanje** [comment]
Can I be assigned this one?

**Comment by jpenanje** [comment]
Work completed. Push the code to my branch before it can be merged

**Comment by jpenanje** [comment]
I do not have access to push

**Comment by ExcelDurant** [comment]
> I do not have access to push

You can create a pull request if you have forked the project. If not you can fork the project and from there you can create a pull request.
You can read this to see how to proceed: [Creating a pull request from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by jpenanje** [comment]
Completed

**Comment by jpenanje** [comment]
Approved and merged by Mr Fenn
