### ISSUE TITLE
Click on LACSODEC logo to redirect to the homepage

### ISSUE THREAD

**Issue by jpenanje** [whilesmart/lasodec#58]
Most site logos when clicked on, redirects the site to the homepage. Is this under consideration?

**Comment by Fenn-CS** [comment]
When was this completed?

**Comment by jpenanje** [comment]
> When was this completed?

a few minutes ago. PR submitted already

**Comment by Fenn-CS** [comment]
You can't (should not) close an issue until, the solution is accepted. Also always mention the issue in the PR for linking.

**Comment by jpenanje** [comment]
> You can't (should not) close an issue until, the solution is accepted. Also always mention the issue in the PR for linking.

Understood boss! My bad🙏
