### ISSUE TITLE
Register Expert Profile: Important fields lacking and typing error

### ISSUE THREAD

**Issue by jpenanje** [whilesmart/lasodec#62]
I think fields for phone number and email address should be added.

Typing error: Certification instead of Certifivation.

@Flovet-stack

**Comment by jpenanje** [comment]
I can handle with issue with your permission. Waiting for your go ahead

**Comment by Fenn-CS** [comment]
Expert profile is connected to a registered user to this is already the case.

**Comment by jpenanje** [comment]
> Expert profile is connected to a registered user to this is already the case.

Oh ok! Understood
