### ISSUE TITLE
Setup Laravel Orchid for the Project

### ISSUE THREAD

**Issue by ExcelDurant** [whilesmart/lasodec#9]
We need to integrate `Laravel Orchid` into our project to manage our application's backend functionality effectively. `Laravel Orchid` will provide us with a web-based, customizable administration panel to handle `CRUD` operations, `data-management` functionality, and other important backend tasks.

We will need to install `Laravel Orchid` using `Composer` and configure it within our project to take advantage of its features. Additionally, we will need to integrate it with our existing project structure and ensure that our `models`, `controllers`, and `views` are correctly configured to work with `Laravel Orchid`.

Once `Laravel Orchid` is fully integrated, we can use it to manage everything from user and role management to database table creation and management, saving us a significant amount of time and effort.

**Comment by Fenn-CS** [comment]
Link this to the appropriate PR and close the issue.
